### PR TITLE
Rename "Client Type" options

### PR DESCRIPTION
**Pull request by brendannee**
Rename from Confidential / Public to something more sane

### CODE REVIEW

**Comment by brendannee** [comment]
I agree that it is confusing, and "oAuth Page Flow" and "Direct Auth Flow" are the best names.  Maru, what do you think?

**Comment by maroux** [comment]
@a18n Just to clarify what those mean (in case you didn't already know):

Confidential apps can keep a secret, that is apps that have a server component. 
Public apps can't keep a secret, eg, mobile or JS apps. JS apps = fully JS, no backend, like Dashboard. Spot Angels is using OAuth page flow, but they still can't keep a secret since it'll be exposed. 

And I just realized that `oAuth Page Flow` and `Direct Auth Flow` are actually not correct since mobile apps will still use OAuth Page Flow. Also, if by `Direct Auth Flow` you mean using username and password to authenticate, then that's a privilege available only to Automatic apps, so there's not much point is making that distinction. 

I suggest we change (if at all) to just:

`Web/Server Applications (Confidential)` 
`Mobile and JS Native Applications (Public)` 

(Reason for still keeping confidential/public is because that's what it's called in the code and I really don't want to refactor code for this). I agree that it's not really worth a long discussion since these names are only internal.

The only difference between those options is - some apps get longer access token expiration because they can keep a secret, and they get to not pass `secret` to authenticate.

**Comment by a18n** [comment]
As you like it. :)  I'm going to stay out of this one... just wanted the feedback heard.

**Comment by brendannee** [comment]
I thought that "Mobile and JS Native Applications" meant can use username and password to authenticate like dashboard - how do we control which Automatic applications get to do that?

**Comment by a18n** [comment]
sorry to bother.… re-reading your comment above maru I think I might not understand what the "Public" flow is. Can you tell me if this is what is happening?

Login with Automatic Button requests oAuth page using client_id
→ get oAuth page and sign-in
→ Automatic passes back authorization code to the redirect
→ App gets auth_code, sends back up WITHOUT a secret ???
→ Automatic passes access token anyway, even with no secret given???

**Pull request closed without merging**
